# Generated by Django 4.2.16 on 2024-12-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_role_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floormap',
            name='description',
            field=models.TextField(default='Default description', verbose_name='Type here'),
        ),
        migrations.AddField(
            model_name='floormap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_maps/'),
        ),
        migrations.AddField(
            model_name='floormap',
            name='num_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floormap',
            name='num_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floormap',
            name='num_kitchens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='floormap',
            name='num_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='floormap',
            name='num_washrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='floor_type',
            field=models.CharField(default='Residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='name',
            field=models.CharField(default='Unnamed Floor Map', max_length=100),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
