# Generated by Django 4.2.16 on 2024-12-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_floormap_description_floormap_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floormap',
            name='num_bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='num_bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='num_kitchens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='num_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='floormap',
            name='num_washrooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
