# Generated by Django 4.2.16 on 2024-12-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_floormap_length_alter_floormap_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='floormap',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
